# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7773534edb8d722352b675871c10489940de64c9c1690d1c86be5986aaf0d6af8edf7b0779e46c03f91932ca4883e5cddca287cb701a61ba291c46233a257aa7

test:
  secret_key_base: aefd300bba301cd1fdb55cfd9da4b4d1c72588fca09ead92a5f8d8c47f5268a09b85c1013371b3488ea135929998f6b4d326c9eebbc1ccd28512cd04d874f4fc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
